apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: pipeline
spec:
  params:
  tasks:
    - name: pipeline-hello-world-task
      taskRef:
        name: hello-world-task
      params:       
