apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: hello-world-task
spec:
  inputs:
    params:
  steps:
    - name: hello-world
      image: alpine
      env:
      command: ["/bin/sh", "-c"]
      args:
        - echo "Hello, world.";
          free;
  volumes:
